// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Repository.Config;
using DbContext = Repository.Config.DbContext;

namespace Repository.Migrations
{
    [DbContext(typeof(DbContext))]
    [Migration("20190522205832_CreatePeopleTable")]
    partial class CreatePeopleTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ITCalculator.Entities.PersonEntity", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("CPF")
                        .HasColumnName("cpf");

                    b.Property<int>("DependentsAmount")
                        .HasColumnName("dependents_amount");

                    b.Property<double>("MonthlyGrossRevenue")
                        .HasColumnName("monthly_gross_revenue");

                    b.Property<string>("PersonName")
                        .HasColumnName("person_name");

                    b.HasKey("PersonId");

                    b.ToTable("People");
                });
#pragma warning restore 612, 618
        }
    }
}
